name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    uses: boegholm/Workflows/.github/workflows/BuildTestPackPushv6.yml@master
    with:
      projects: "['FTypBoxReader/FTypBoxReader.csproj']"
    secrets:
      nuser: ${{ secrets.NUSER }}
      npass: ${{ secrets.NPASS }}
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
      NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
      NUGET_SYM_SOURCE: ${{ secrets.NUGET_SYM_SOURCE }}